Repository samz5320/Data4ALL, pull requests merged in 2021-10, with the labels that each got.

#20 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: hacktoberfest-accepted

#62 Modified Readme
  README.md
  assets/images/dark_theme.png
  assets/images/data4all_poster.gif
  assets/images/light_theme.png
Labels: documentation, major

#76 Drinking Water Potability Dataset
  datasets/drinking_water_potability.csv
  index.html
Labels: hacktoberfest-accepted

#66 Added Datasets
  datasets/Github_repos.csv
  datasets/airports-extended.csv
  datasets/movie_titles.csv
Labels: requested-changes

#104 Update Readme
  README.md
Labels: hacktoberfest-accepted
